In [1]:
import pandas as pd

In [2]:
migration2017 = pd.read_excel('../cleaned excels/State_to_State_Migrations_Table_2017_clean2.xls')
migration2018 = pd.read_excel('../cleaned excels/State_to_State_Migrations_Table_2018_clean2.xls')
migration2019 = pd.read_excel('../cleaned excels/State_to_State_Migrations_Table_2019_clean2.xls')

In [3]:
migration2017.head()

,Year,Before Tax Change,Current residence in,Total Population,Same house 1 year ago,Same state of residence 1 year ago,Total_Incoming,Total_Outgoing,Net Migration,Net Migrationpn,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico,US Island Area,Foreign Country
0,2017,yes,Alabama,4819343,4158224,535649,111803,101466,10337,positive,...,998.0,0.0,4277.0,1289.0,1070.0,1121.0,104.0,476,0,13191
1,2017,yes,Alaska,730874,595804,98168,30199,42972,-12773,negative,...,465.0,0.0,360.0,3653.0,0.0,2500.0,6.0,0,965,5738
2,2017,yes,Arizona,6935358,5717189,911120,261727,163214,98513,positive,...,8594.0,96.0,3593.0,14392.0,318.0,3897.0,997.0,438,91,44793
3,2017,yes,Arkansas,2968395,2509717,370309,79411,69850,9561,positive,...,657.0,0.0,1087.0,1539.0,0.0,958.0,12.0,573,0,8385
4,2017,yes,California,39085984,34009331,4234770,523131,661026,-137895,negative,...,9925.0,895.0,21162.0,33143.0,789.0,9348.0,1395.0,1864,842,316046

In [4]:
migration2018.head()

,Year,Before Tax Change,Current residence in,Total Population,Same house 1 year ago,Same state of residence 1 year ago,Total_Incoming,Total_Outgoing,Net Migration,Net Migrationpn,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico,US Island Area,Foreign Country
0,2018,no,Alabama,4832358,4173026,534914,109301,98194,11107,positive,...,79.0,0.0,5221.0,2125.0,176.0,996.0,74.0,957,893,13267
1,2018,no,Alaska,727164,608707,81229,32099,39246,-7147,negative,...,410.0,5.0,654.0,2558.0,0.0,340.0,192.0,344,267,4518
2,2018,no,Arizona,7090137,5887700,888452,273714,179586,94128,positive,...,5828.0,37.0,4956.0,17560.0,29.0,7788.0,929.0,1289,1449,37533
3,2018,no,Arkansas,2975961,2539294,354774,73179,69724,3455,positive,...,712.0,0.0,900.0,1328.0,72.0,130.0,0.0,1693,0,7021
4,2018,no,California,39114889,34232867,4092388,501023,691145,-190122,negative,...,9440.0,1641.0,17725.0,38007.0,1246.0,5364.0,1526.0,1250,3712,283649

In [5]:
migration2019.head()

,Year,Before Tax Change,Current residence in,Total Population,Same house 1 year ago,Same state of residence 1 year ago,Total_Incoming,Total_Outgoing,Net Migration,Net Migrationpn,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico,US Island Area,Foreign Country
0,2019,no,Alabama,4849509,4197698,534842,104780,98704,6076,positive,...,2083.0,0.0,2876.0,1883.0,421.0,1307.0,0.0,338,103,11748
1,2019,no,Alaska,722063,609362,74375,34031,50134,-16103,negative,...,1092.0,44.0,2216.0,1435.0,355.0,228.0,242.0,37,17,4241
2,2019,no,Arizona,7200620,6038776,861935,253295,173631,79664,positive,...,8917.0,662.0,3837.0,17636.0,237.0,3688.0,664.0,970,152,45492
3,2019,no,Arkansas,2989054,2559444,361762,59723,64524,-4801,negative,...,710.0,0.0,671.0,571.0,133.0,797.0,1109.0,302,0,7823
4,2019,no,California,39084048,34394220,3943139,480204,653551,-173347,negative,...,8504.0,784.0,24506.0,31882.0,303.0,4811.0,1159.0,1780,2887,261818

In [6]:
combined = migration2017.append([migration2018, migration2019], ignore_index = False)
combined

,Year,Before Tax Change,Current residence in,Total Population,Same house 1 year ago,Same state of residence 1 year ago,Total_Incoming,Total_Outgoing,Net Migration,Net Migrationpn,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico,US Island Area,Foreign Country
0,2017,yes,Alabama,4819343,4158224,535649,111803,101466,10337,positive,...,998.0,0.0,4277.0,1289.0,1070.0,1121.0,104.0,476,0,13191
1,2017,yes,Alaska,730874,595804,98168,30199,42972,-12773,negative,...,465.0,0.0,360.0,3653.0,0.0,2500.0,6.0,0,965,5738
2,2017,yes,Arizona,6935358,5717189,911120,261727,163214,98513,positive,...,8594.0,96.0,3593.0,14392.0,318.0,3897.0,997.0,438,91,44793
3,2017,yes,Arkansas,2968395,2509717,370309,79411,69850,9561,positive,...,657.0,0.0,1087.0,1539.0,0.0,958.0,12.0,573,0,8385
4,2017,yes,California,39085984,34009331,4234770,523131,661026,-137895,negative,...,9925.0,895.0,21162.0,33143.0,789.0,9348.0,1395.0,1864,842,316046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,2019,no,Virginia,8439982,7201805,903735,264855,276849,-11994,negative,...,1736.0,1633.0,NaN,6580.0,5518.0,1518.0,167.0,1896,185,67506
47,2019,no,Washington,7527366,6253469,977928,231956,199758,32198,positive,...,5440.0,391.0,6656.0,NaN,275.0,1456.0,626.0,318,1465,62230
48,2019,no,West Virginia,1773280,1563611,164739,39548,40460,-912,negative,...,0.0,19.0,6008.0,129.0,NaN,41.0,0.0,606,0,4776
49,2019,no,Wisconsin,5760481,5001140,634732,107973,101668,6305,positive,...,808.0,0.0,1878.0,1682.0,572.0,NaN,1417.0,513,0,16123
50,2019,no,Wyoming,572884,473128,68127,30247,23287,6960,positive,...,1746.0,0.0,415.0,885.0,308.0,27.0,NaN,0,0,1382

In [7]:
combined = combined.fillna(0)

In [8]:
combined.to_excel("combined_data.xls", index= False, header= True)